from requests import get
dog_facts = get("https://dog-facts-api.herokuapp.com/api/v1/resources/dogs/all")

print(dog_facts.text)
count = 0
while (count < 50):
    count = count + 1
    cat_fact = get("https://meowfacts.herokuapp.com")
    cat_loop = 0
    while (cat_loop < 10):
        cat_loop = cat_loop + 1
        print(cat_fact.text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)
print(get("https://zoo-animal-api.herokuapp.com/animals/rand").text)